language: node_js
node_js:
  - "12"

cache: npm

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test:coverage
    - stage: npm release
      if: tag IS present
      node_js: "12"
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
